import { LeftNav } from './components'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Immunefiles',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="relative flex">
        <LeftNav/>
        {children}
      </body>
    </html>
  )
}
